### ISSUE TITLE
Option for counts/labels in plotly

### ISSUE THREAD

**Issue by joannawolthuis** [gaospecial/ggVennDiagram#21]
Hi there! Thanks for all you work on this package and addressing my earlier issue :) I noticed that you removed the numbers in the intersections in plotly plots for the new release. I was wondering if you'd consider adding those back in (perhaps optional?) as it would aid me in my analyses.

Thank you and kind regards,
Joanna

**Comment by gaospecial** [comment]
Thanks for your feedback.

I have added this feature in https://github.com/gaospecial/ggVennDiagram/commit/546ebe5148ef56dbc38b97f84a431a48a327e1a7

Since plotly is not fine compatible with sf object (see https://github.com/ropensci/plotly/issues/1641#issuecomment-550477069) , I just set label count as the archor to show item members in tooltip.

```r
x <- list(A=1:5,B=2:7,C=3:6,D=4:9)
ggVennDiagram(x, show_intersect = T)
```

will give

![image](https://user-images.githubusercontent.com/107597/117231248-6e3ce280-ae51-11eb-95d0-ae4b4b6423b9.png)
