### ISSUE TITLE
Keep size proportion for each section [suggestion]

### ISSUE THREAD

**Issue by jgarces02** [gaospecial/ggVennDiagram#62]
Hi @gaospecial, 

Thank you for the nice package. I like the option of coloring according to the numbers in each section... Have you thought about implementing the size instead the color intensity for representing these numbers by section? I mean, than not all sections have the same size but proportional to the internal number, something like in the attached image.

Thank you.

![image](https://github.com/gaospecial/ggVennDiagram/assets/27858969/1927ac2b-f114-41be-a1cb-9e2e37edc4d5)

**Comment by gaospecial** [comment]
To date, there are three major methods to display set relationships, Venn diagram, Euler diagram and UpSet plot ([Conway, Lex, and Gehlenborg 2017](https://venn.bio-spring.top/applications#ref-conwayUpSetRPackageVisualization2017)). The UpSet plot is a state-of-art visualization technique for the quantitative analysis of sets ([Lex et al. 2014](https://venn.bio-spring.top/applications#ref-lexUpSetVisualizationIntersecting2014)), and support unlimited number of sets.

When the number of sets is very large, UpSet plot is more reasonable be choose. By contrast, Venn and Euler are both traditional approaches to finish this task. Euler diagram is area-proportional, and only show relevant relationships.

Since human eye is less sensitive to area than to color, we believe that using color filling to show the difference between different regions is more suitable for ordinary studies.

**Comment by jgarces02** [comment]
It could be a combination of color and size, but it's OK. Thank you.
